Tienda:
  type: entity
  table: tienda
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 100
      fixed: false
      nullable: false
    slug:
      type: string
      length: 100
      fixed: false
      nullable: false
    login:
      type: string
      length: 10
      fixed: false
      nullable: false
    password:
      type: string
      length: 255
      fixed: false
      nullable: false
    salt:
      type: string
      length: 255
      fixed: false
      nullable: false
    descripcion:
      type: text
      nullable: false
    direccion:
      type: text
      nullable: false
  manyToOne:
    ciudad:
      targetEntity: Ciudad
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ciudad_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
